"""CellQuorum visualization module."""

from __future__ import annotations

from cellquorum.visualization.publication import (
    DISEASE_COLOR,
    DOUBLET_COLOR,
    NORMAL_COLOR,
    QC_FAIL_COLOR,
    TEXT_COLOR,
    add_panel_label,
    add_stat_bracket,
    categorical_embedding,
    categorical_palette,
    cell_type_palette,
    clean_axis,
    condition_palette,
    pvalue_to_stars,
    save_publication_figure,
    set_publication_style,
    violin_with_stats,
)
from cellquorum.visualization.style import (
    BACKGROUND_BLUE,
    BACKGROUND_GRAY,
    BACKGROUND_RED,
    CELLQUORUM_BLUE,
    CELLQUORUM_CLUSTER_COLORS,
    CELLQUORUM_FIGSIZE_SMALL,
    CELLQUORUM_FIGSIZE_SQUARE,
    CELLQUORUM_FIGSIZE_WIDE,
    CELLQUORUM_GRAY,
    CELLQUORUM_RED,
    add_dashed_reference_lines,
    add_directional_arrows,
    add_statistical_annotation_box,
    add_volcano_background_panels,
    apply_cellquorum_axis_style,
    apply_cellquorum_theme,
    get_cellquorum_colors,
    save_cellquorum_figure,
)

__all__ = [
    "CELLQUORUM_BLUE",
    "CELLQUORUM_RED",
    "CELLQUORUM_GRAY",
    "BACKGROUND_BLUE",
    "BACKGROUND_GRAY",
    "BACKGROUND_RED",
    "CELLQUORUM_CLUSTER_COLORS",
    "CELLQUORUM_FIGSIZE_SMALL",
    "CELLQUORUM_FIGSIZE_WIDE",
    "CELLQUORUM_FIGSIZE_SQUARE",
    "apply_cellquorum_theme",
    "apply_cellquorum_axis_style",
    "save_cellquorum_figure",
    "get_cellquorum_colors",
    "add_volcano_background_panels",
    "add_dashed_reference_lines",
    "add_directional_arrows",
    "add_statistical_annotation_box",
    "NORMAL_COLOR",
    "DISEASE_COLOR",
    "QC_FAIL_COLOR",
    "DOUBLET_COLOR",
    "TEXT_COLOR",
    "set_publication_style",
    "save_publication_figure",
    "condition_palette",
    "categorical_palette",
    "cell_type_palette",
    "add_panel_label",
    "add_stat_bracket",
    "pvalue_to_stars",
    "violin_with_stats",
    "clean_axis",
    "categorical_embedding",
]
