"""CellQuorum visualization module.

The single canonical style module is :mod:`cellquorum.visualization.figstyle`.
Every public name below resolves to figstyle so existing importers of
``cellquorum.visualization`` keep working after the consolidation.
"""

from __future__ import annotations

from cellquorum.visualization.figstyle import (
    BACKGROUND_BLUE,
    BACKGROUND_GRAY,
    BACKGROUND_RED,
    CATEGORICAL_PALETTE,
    CELLQUORUM_BLUE,
    CELLQUORUM_CLUSTER_COLORS,
    CELLQUORUM_FIGSIZE_LARGE,
    CELLQUORUM_FIGSIZE_SMALL,
    CELLQUORUM_FIGSIZE_SQUARE,
    CELLQUORUM_FIGSIZE_WIDE,
    CELLQUORUM_GRAY,
    CELLQUORUM_RED,
    DOUBLET_COLOR,
    LE_RED,
    NORMAL_BLUE,
    NORMAL_COLOR,
    QC_FAIL_COLOR,
    SEQUENTIAL_CMAP,
    TEXT,
    TEXT_COLOR,
    add_dashed_reference_lines,
    add_directional_arrows,
    add_embedding_scalebar,
    add_stat_bracket,
    add_statistical_annotation_box,
    add_volcano_background_panels,
    apply_cellquorum_axis_style,
    apply_cellquorum_theme,
    categorical_embedding,
    categorical_palette,
    cell_type_palette,
    clean_axis,
    condition_palette,
    diverging_norm,
    embedding_limits,
    get_cellquorum_colors,
    get_group_palette,
    palette_colors,
    panel_letter,
    pvalue_to_stars,
    remove_embedding_axes,
    save_cellquorum_figure,
    save_figure,
    save_publication_figure,
    set_publication_style,
    set_style,
    significance_stars,
    violin_with_stats,
)

__all__ = [
    "BACKGROUND_BLUE",
    "BACKGROUND_GRAY",
    "BACKGROUND_RED",
    "CATEGORICAL_PALETTE",
    "CELLQUORUM_BLUE",
    "CELLQUORUM_CLUSTER_COLORS",
    "CELLQUORUM_FIGSIZE_LARGE",
    "CELLQUORUM_FIGSIZE_SMALL",
    "CELLQUORUM_FIGSIZE_SQUARE",
    "CELLQUORUM_FIGSIZE_WIDE",
    "CELLQUORUM_GRAY",
    "CELLQUORUM_RED",
    "DOUBLET_COLOR",
    "LE_RED",
    "NORMAL_BLUE",
    "NORMAL_COLOR",
    "QC_FAIL_COLOR",
    "SEQUENTIAL_CMAP",
    "TEXT",
    "TEXT_COLOR",
    "add_dashed_reference_lines",
    "add_directional_arrows",
    "add_embedding_scalebar",
    "add_statistical_annotation_box",
    "add_stat_bracket",
    "add_volcano_background_panels",
    "apply_cellquorum_axis_style",
    "apply_cellquorum_theme",
    "categorical_embedding",
    "categorical_palette",
    "cell_type_palette",
    "clean_axis",
    "condition_palette",
    "diverging_norm",
    "embedding_limits",
    "get_cellquorum_colors",
    "get_group_palette",
    "palette_colors",
    "panel_letter",
    "pvalue_to_stars",
    "remove_embedding_axes",
    "save_cellquorum_figure",
    "save_figure",
    "save_publication_figure",
    "set_publication_style",
    "set_style",
    "significance_stars",
    "violin_with_stats",
]
